<?xml version="1.0" encoding="utf-8" ?>
<DUMMY>
  <DEFINE>
    <!-- standard icon buttons -->
    <CUS_ON_OFF_BUTTON base_type="IMAGE_PARAM_BUTTON" image="$THEME_PATH$/buttons/on_off_button.png" image_focus="$THEME_PATH$/buttons/on_off_button_hover.png" cursor="system::hand"/>
    <CUS_CHECK_BOX base_type="IMAGE_PARAM_BUTTON" image="$THEME_PATH$/buttons/check_box.bmp" image_orientation="horizontal" cursor="system::hand"/>
    
    <!-- Buttons that may be used to include text -->
    <CUS_STATUS_BUTTON_80 base_type="IMAGE_PARAM_BUTTON" image="$THEME_PATH$/buttons/status_rect_button80.png" image_focus="$THEME_PATH$/buttons/status_rect_button80_hover.png" cursor="system::hand"/>
    
    <CUS_DROPDOWN_PARAM_BUTTON_90 base_type="IMAGE_PARAM_MENU_BUTTON" image="$THEME_PATH$/buttons/dropdown90.png" image_focus="$THEME_PATH$/buttons/dropdown90_hover.png" cursor="system::hand"/>
     
     <CUS_DROPDOWN_ACTION_BUTTON_90 base_type="IMAGE_ACTION_BUTTON" image="$THEME_PATH$/buttons/dropdown90.png" image_focus="$THEME_PATH$/buttons/dropdown90_hover.png" cursor="system::hand"/>

    <CUS_DROPDOWN_PARAM_BUTTON_80 base_type="IMAGE_PARAM_MENU_BUTTON" image="$THEME_PATH$/buttons/dropdown80.png" cursor="system::hand"/>
     
     <CUS_DROPDOWN_ACTION_BUTTON_80 base_type="IMAGE_ACTION_BUTTON" image="$THEME_PATH$/buttons/dropdown80.png" cursor="system::hand"/>
     
 
  </DEFINE>
</DUMMY>